name: 🐞 Bug Report
description: Create a report to help us improve Tevico Community
labels: ["bug", "status/needs-triage"]

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please describe the bug and steps to reproduce it.
      placeholder: |
        1. What command or action were you running?
        2. What happened?
        3. What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      options:
        - Git clone
        - Pip package
        - Docker
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: environment-info
    attributes:
      label: Environment Information
      description: Tell us about your environment
      placeholder: |
        - Tevico version: (run `tevico --version`)
        - Operating system:
        - Where you're running Tevico (EC2, local, etc):
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Screenshots
      description: If applicable, include logs or screenshots of the issue
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help us solve the issue
    validations:
      required: false
