name: 💡 Feature Request
description: Suggest an idea or enhancement for `tevico-community`
labels: ["feature-request", "status/needs-triage"]

body:
  - type: textarea
    id: problem
    attributes:
      label: New Feature Motivation
      description: Is your feature request related to a problem? Please describe the problem and how it impacts you.
      placeholder: |-
        1. Provide a clear and concise description of the problem.
           Ex. "I'm always frustrated when..."
        2. Explain how this issue affects your workflow or usage of `tevico-community`.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or enhancement you'd like to see in `tevico-community`.
      placeholder: |-
        1. What do you want to happen?
        2. Describe how the feature should behave or interact.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.
      placeholder: |-
        1. What other options have you explored?
        2. Why do you think this feature is better than the alternatives?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, use cases, or screenshots that might help explain the feature request.
      placeholder: |-
        1. Provide any additional information here.
        2. Include screenshots, diagrams, or use cases if applicable.
    validations:
      required: false
