name: 💡 Feature Request
description: Suggest an idea for tevico-community
labels: ["feature-request", "status/needs-triage"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: Describe the issue you're facing that led to this request.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your proposed feature or enhancement.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other details that might help explain your request.
      placeholder: Add screenshots, alternatives considered, or other relevant information.
    validations:
      required: false
